### ISSUE TITLE
Better End Sky seems not working when the dragon is alive

### ISSUE THREAD

**Issue by FlamingTM** [azuredao8/BetterEndSky#2]
Better End Sky seems to not work while the dragon is still alive, I have no clue if this is a bug so I'm just checking if that's a bug or not, also if it's not a bug a config to turn it on permanently would be great. :D

**Comment by azuredao8** [comment]
Minecraft 1.17 in the course of its development changed quite a number of issues related to fog, so I can only assume it must have something to do with that. I think your best bet might be to find/request a mod which removes the Ender Dragon bossfight fog.
